create table reviews (
    id integer primary key generated by default as identity,
    review_user text not null,
    review_heading text not null,
    review_content text not null,
    review_star integer not null,
    review_date timestamptz default now() not null
);

alter table reviews
    add column
        item_id integer references items(id) on delete cascade not null;