create table reviews (
    id integer primary key generated by default as identity,
    user text not null,
    heading text not null,
    content text not null,
    star integer not null,
    review_date timestamptz default now() not null,
);

alter table reviews
    add column
        item_id integer references items(id) on delete cascade not null;